### ISSUE TITLE
myglide加载完图片后什么时候关闭InputStream

### ISSUE THREAD

**Issue by DaneChen** [rain9155/P2P#2]
有幸学习到这个项目，非常感谢！有点疑问请教下：

在myglide中，EngineDecodeJob 类
private Bitmap cacheData(InputStream inputStream) throws IOException {
        if(!isSkipDisk && mDiskCache != null){
            mDiskCache.put(mKey, inputStream);
            return loadFromDiskCache(mKey);
        }
        if(isCancel){
            return null;
        }
        if(inputStream instanceof FileInputStream){
            return decodeBitmapFromFileInputStream(
                    (FileInputStream) inputStream,
                    mWidth,
                    mHeight);
        }else {
            return decodeBitmapFromInputStream(
                    inputStream,
                    mWidth,
                    mHeight);
        }
    }

这个方法中，走到最后InputStream没有关闭？这是为啥

**Comment by rain9155** [comment]
这个是一个bug，我现在已经在解析完图片后关闭掉inputStream了，可以看[750260](https://github.com/rain9155/P2P/commit/750260b15b337f2535e4292aaae375cafddfec30)提交，感谢指出错误！
